// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sokgjnkfazxhjqatfetk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNva2dqbmtmYXp4aGpxYXRmZXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNTU2MDUsImV4cCI6MjA1OTczMTYwNX0.RaIy3kOHBfoH1XS9xiHzze2KaWu7qorv7mBJRWw6ZkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});